project_id = "bqqyxlvyvtwvfgrnbmlc"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://bqqyxlvyvtwvfgrnbmlc.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[storage]
enabled = true
file_size_limit = "50MB"

[functions]

[analytics]
enabled = false